```{r Set Up, include=FALSE}
install.packages("tidyverse")
install.packages("readxl")
install.packages("writexl")


library(tidyverse)
library(readxl)
library(dplyr)
library(writexl)
```

```{r}
#imported cleaned data of positive labour market impact assesment (LMIA) that are currently active (2019Q4 and 2020Q1)

employers_raw <- read_excel("LMIA_canada.xlsx")
employers <- as.data.frame(employers_raw)
quebec_raw <- read_excel("LMIA_quebec.xlsx")
quebec <- as.data.frame(quebec_raw)
```


```{r}
#filtered LMIA made in ALberta, made a total count of migrant workers per location name#


alberta_employers <- employers %>% filter(Province == "Alberta")

job_num_alberta <- alberta_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_alberta,'job_num_al.csv')

```

```{r}
#filtered LMIA made in BC, made a total count of migrant workers per location name#

bc_employers <- employers %>% filter(Province == "British Columbia")

job_num_bc <- bc_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_bc,'job_num_bc.csv')

```

```{r}
#filtered LMIA made Manitoba, made a total count of migrant workers per location name#
manitoba_employers <- employers %>% filter(Province == "Manitoba")

job_num_ma <- manitoba_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_ma,'job_num_ma.csv')
```

```{r}
#filtered LMIA made in New Brunswick, made a total count of migrant workers per location name#
nb_employers <- employers %>% filter(Province == "New Brunswick")

job_num_nb <- nb_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )
#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_nb,'job_num_nb.csv')
```

```{r}
#filtered LMIA made in Nove Scotia, made a total count of migrant workers per location name#
ns_employers <- employers %>% filter(Province == "Nova Scotia")

job_num_ns <- ns_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )
#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_ns,'job_num_ns.csv')
```

```{r}

#filtered LMIA made in Ontario, made a total count of migrant workers per location name#
on_employers <- employers %>% filter(Province == "Ontario")

job_num_on <- on_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )
#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_on,'job_num_on.csv')
```

```{r}
#filtered LMIA made in New Brunswick, made a total count of migrant workers per location name#
pei_employers <- employers %>% filter(Province == "Prince Edward Island")

job_num_pei <- pei_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_pei,'job_num_pei.csv')
```

```{r}
#filtered LMIA made in Quebec, made a total count of migrant workers by postal code, by postal code because Gov. Website matches health region by postal code, not location name#
qu_employers <- quebec %>% filter(Province == "Quebec")

job_num_qu <- qu_employers %>%
  group_by(Postal) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_qu,'job_num_qu_postal.csv')
```

```{r}
#filtered LMIA made in Saskatchewan, made a total count of migrant workers per location name#
sa_employers <- employers %>% filter(Province == "Saskatchewan")

job_num_sa <- sa_employers %>%
  group_by(Location) %>%
  summarise(
    n = n(),
    jobs = sum(`Job Num`)
  ) %>%
  filter(
    n > 0,
    jobs > 0
  )

#exported file, was cities were then matched to health regions in excel#
write.csv(job_num_sa,'job_num_sa.csv')

#All csv files were furthered cleaned and converted to xlsx#
```

