---
title: "census_density_agedemo"
output: pdf_document
---

```{r}
library(tidyverse)
library(readxl)
```

---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Importing Case Data}
library(tidyverse)
#Importing covid-19 cases data from github
case <- readr::read_csv(
  file = "https://raw.githubusercontent.com/ishaberry/Covid19Canada/master/cases.csv",
  col_names = TRUE,
  col_types = c("cccccccccccccccc")
)

case_filter <- case%>%
    dplyr::select(
    case_id,
    health_region,
    travel_history_country,
    age
 ) 
glimpse(case)

```

```{r Filtering Cases by Age}
#filters cases by age categories (every 10 yrs), and summarized amount of cases in each age category per region#

#filtering cases in people < 10 yrs old, summarizing amount of cases per region
cases_under_10 <- filter(summary,age=="<10"|age=="<1"|age=="2")
cases_region_under10 <- cases_under_10 %>%
  group_by(health_region,province) %>%
  summarize(cases_under10 = n())
cases_region_under10

#filtering cases in people between 10 and 19 yrs old, summarizing amount of cases per region
cases_under_20 <- filter(summary,age=="<19"|age=="<20"|age=="<18"|age=="10-19")
cases_region_under20 <- cases_under_20 %>%
  group_by(health_region,province) %>%
  summarize(cases_under20 = n())
cases_region_under20

#filtering cases in people 20 to 29 yrs old, summarizing amount of cases per region
cases_20s <- filter(summary,age=="20-29")
cases_region_20 <- cases_20s %>%
  group_by(health_region,province) %>%
  summarize(cases_20 = n())
cases_region_20

#filtering cases in people 30 to 39 yrs old, summarizing amount of cases per region
cases_30s <- filter(summary,age=="30-39")
cases_region_30 <- cases_30s %>%
  group_by(health_region,province) %>%
  summarize(cases_30 = n())
cases_region_30

#filtering cases in people 40 to 49 yrs old, summarizing amount of cases per region
cases_40s <- filter(summary,age=="40-49")
cases_region_40 <- cases_40s %>%
  group_by(health_region,province) %>%
  summarize(cases_40 = n())
cases_region_40

#filtering cases in people 50 to 59 yrs old, summarizing amount of cases per region
cases_50s <- filter(summary,age=="50-59")
cases_region_50 <- cases_50s %>%
  group_by(health_region,province) %>%
  summarize(cases_50 = n())
cases_region_50

#filtering cases in people 60 to 69 yrs old, summarizing amount of cases per region
cases_60s <- filter(summary,age=="60-69")
cases_region_60 <- cases_60s %>%
  group_by(health_region,province) %>%
  summarize(cases_60 = n())
cases_region_60

#filtering cases in people 70 to 79 yrs old, summarizing amount of cases per region
cases_70s <- filter(summary,age=="70-79")
cases_region_70 <- cases_70s %>%
  group_by(health_region,province) %>%
  summarize(cases_70 = n())
cases_region_70

#filtering cases in people 80 to 89 yrs old, summarizing amount of cases per region
cases_80s <- filter(summary,age=="80-89")
cases_region_80 <- cases_80s %>%
  group_by(health_region,province) %>%
  summarize(cases_80 = n())
cases_region_80

#filtering cases in people 90 to 99 yrs old, summarizing amount of cases per region
cases_90s <- filter(summary,age=="90-99")
cases_region_90 <- cases_90s %>%
  group_by(health_region,province) %>%
  summarize(cases_90 = n())
cases_region_90

#filtering cases in people 100 to 109 yrs old, summarizing amount of cases per region
cases_100s <- filter(summary,age=="100-109")
cases_region_100 <- cases_100s %>%
  group_by(health_region,province) %>%
  summarize(cases_100 = n())
cases_region_100

#filtering cases that were not reported, summarizing amount of cases per region
cases_NR <- filter(summary,age=="Not Reported")
cases_region_NR <- cases_NR %>%
  group_by(health_region,province) %>%
  summarize(casesNR = n())
cases_region_NR

```
```{r Sort Cases by Health Region}

#merging all data frames from previous chunk together, so one dataframe has amount of cases for each age category per health region
a<-merge(cases_region_under10,cases_region_under20,by=c("health_region","province"),all=TRUE)
b<-merge(a,cases_region_20,by=c("health_region","province"),all=TRUE)
c<-merge(b,cases_region_30,by=c("health_region","province"),all=TRUE)
d<-merge(c,cases_region_40,by=c("health_region","province"),all=TRUE)
e<-merge(d,cases_region_50,by=c("health_region","province"),all=TRUE)
f<-merge(e,cases_region_60,by=c("health_region","province"),all=TRUE)
g<-merge(f,cases_region_70,by=c("health_region","province"),all=TRUE)
h<-merge(g,cases_region_80,by=c("health_region","province"),all=TRUE)
i<-merge(h,cases_region_90,by=c("health_region","province"),all=TRUE)
j<-merge(i,cases_region_100,by=c("health_region","province"),all=TRUE)
case_age<-merge(j,cases_region_NR,by=c("health_region","province"),all=TRUE)
case_age[is.na(case_age)]<-0
case_age
#exported to be cleaning further in excel
write_csv(case_age, "case_age.csv")
```


```{r Importing Census Data}
#importing 2016 census data for health regions
demos <- readr::read_csv("98-401-X2016058_English_CSV_data.csv")
```

```{r Removing regions w no agriculture}
#removed nunavut and ukon due to low amount of cases and little to no agriculture regions
demos_raw<- demos %>% filter(GEO_NAME != "Nunavut")
demos_raw<- demos_raw %>% filter(GEO_NAME != "Yukon")
```

```{r Getting Pop. Density for Health Region}

#obtaining the population density for each health region

pop_density <- demos_raw %>%
  filter(`DIM: Profile of Health Regions (2247)` == "Population density per square kilometre")
pop_density <- pop_density %>%
  dplyr::select(
    "GEO_NAME",
    "Dim: Sex (3): Member ID: [1]: Total - Sex"
  )
pop_density <- pop_density %>%
  rename(
    population_density = `Dim: Sex (3): Member ID: [1]: Total - Sex`
  )

```

```{r Obtaining age data from census/ building function for dataa cleaning}

#function obtains amount of people in each age category for all health regions

age_filter <- function(age) {
  demos_raw %>%
    filter(`DIM: Profile of Health Regions (2247)` == age) %>%
    dplyr::select(
      "GEO_NAME","Dim: Sex (3): Member ID: [1]: Total - Sex",
  )
}

#function that add count of people for each health region. necessary because census data split into five year incrmeents not ten

add_yrs <- function(x) {
  x %>% 
  mutate(pop_total = x$`Dim: Sex (3): Member ID: [1]: Total - Sex.x`+ x$`Dim: Sex (3): Member ID: [1]: Total - Sex.y`, row_num = rownames(x)) %>%
    dplyr::select(
      "GEO_NAME",
      pop_total
    )
    
}

```

```{r Filtering Census data by age}
#obtaining amount of people for each health region using above functions

zero_yrs <- age_filter("0 to 4 years")
fve_yrs <- age_filter("5 to 9 years")
zrs_pop <- merge(zero_yrs, fve_yrs, by = "GEO_NAME")
zrs_pop <- add_yrs(zrs_pop)
zrs_pop <- zrs_pop %>% rename("lessten_total" = "pop_total")

ten_yrs <- age_filter("10 to 14 years")
fftn_yrs <- age_filter("15 to 19 years")
tens_pop <- merge(ten_yrs, fftn_yrs, by = "GEO_NAME")
tens_pop <- add_yrs(tens_pop)
tens_pop <- tens_pop %>% rename("tens_total" = "pop_total")

twnty_yrs <- age_filter("20 to 24 years")
twntyfv_yrs <- age_filter("25 to 29 years")
twntys_pop <- merge(twnty_yrs, twntyfv_yrs, by = "GEO_NAME")
twntys_pop <- add_yrs(twntys_pop)
twntys_pop <- twntys_pop %>% rename("twentys_total" = "pop_total")

thrty_yrs <- age_filter("30 to 34 years")
thrtyfv_yrs <- age_filter("35 to 39 years")
thrtys_pop <- merge(thrty_yrs, thrtyfv_yrs, by = "GEO_NAME")
thrtys_pop <- add_yrs(thrtys_pop)
thrtys_pop <- thrtys_pop %>% rename("thirtys_total" = "pop_total")

frty_yrs <- age_filter("40 to 44 years")
frtyfv_yrs <- age_filter("45 to 49 years")
frtys_pop <- merge(frty_yrs, frtyfv_yrs, by = "GEO_NAME")
frtys_pop <- add_yrs(frtys_pop)
frtys_pop <- frtys_pop %>% rename("fourtys_total" = "pop_total")

ffty_yrs <- age_filter("50 to 54 years")
fftyfv_yrs <- age_filter("55 to 59 years")
fftys_pop <- merge(ffty_yrs, fftyfv_yrs, by = "GEO_NAME")
fftys_pop <- add_yrs(fftys_pop)
fftys_pop <- fftys_pop %>% rename("fiftys_total" = "pop_total")

sxty_yrs <- age_filter("60 to 64 years")
sxtyfv_yrs <- age_filter("65 to 69 years")
sxtys_pop <- merge(sxty_yrs, sxtyfv_yrs, by = "GEO_NAME")
sxtys_pop <- add_yrs(sxtys_pop)
sxtys_pop <- sxtys_pop %>% rename("sixtys_total" = "pop_total")

svnty_yrs <- age_filter("70 to 74 years")
svntyfv_yrs <- age_filter("75 to 79 years")
svntys_pop <- merge(svnty_yrs, svntyfv_yrs, by = "GEO_NAME")
svntys_pop <- add_yrs(svntys_pop)
svntys_pop <- svntys_pop %>% rename("seventys_total" = "pop_total")

ehty_yrs <- age_filter("80 to 84 years")
ehtyfv_yrs <- age_filter("85 to 89 years")
ehtys_pop <- merge(ehty_yrs, ehtyfv_yrs, by = "GEO_NAME")
ehtys_pop <- add_yrs(ehtys_pop)
ehtys_pop <- ehtys_pop %>% rename("eightys_total" = "pop_total")

#case data category is for 90+, had to add census data for three age categories, not two. 
nnty_yrs <- age_filter("90 to 94 years")
nntyfv_yrs <- age_filter("95 to 99 years")
nntys_pop <- merge(nnty_yrs, nntyfv_yrs, by = "GEO_NAME")
hndrd_yrs <- age_filter("100 years and over")
nntyplus_pop <- merge(nntys_pop, hndrd_yrs, by = "GEO_NAME")
nntyplus_pop <- nntyplus_pop %>% mutate(ninetyover_total = nntyplus_pop$`Dim: Sex (3): Member ID: [1]: Total - Sex.x`+ nntyplus_pop$`Dim: Sex (3): Member ID: [1]: Total - Sex.y`+ nntyplus_pop$`Dim: Sex (3): Member ID: [1]: Total - Sex`) %>%
   dplyr::select(
      "GEO_NAME",
      ninetyover_total
    )

```

```{r Compiling dataset with total pop. of age categories by health region}
#merges the dataframes made in the above code chunk, so that one data frame contains amount of people in each age category per health region
test <- merge(zrs_pop, tens_pop, by = "GEO_NAME")
test <- merge(test, twntys_pop, by = "GEO_NAME")
test <- merge(test, thrtys_pop, by = "GEO_NAME")
test <- merge(test, frtys_pop, by = "GEO_NAME")
test <- merge(test, fftys_pop, by = "GEO_NAME")
test <- merge(test, sxtys_pop, by = "GEO_NAME")
test <- merge(test, svntys_pop, by = "GEO_NAME")
test <- merge(test, ehtys_pop, by = "GEO_NAME")
test <- merge(test, nntyplus_pop, by = "GEO_NAME")

#sums amount of people in each age category to get total population for each health region
columns= c("lessten_total", "tens_total", "twentys_total", "thirtys_total", "fourtys_total", "fiftys_total", "sixtys_total", "seventy_total", "eightys_total", "ninetyover_total")

test$pop_total = rowSums(test[,c(-1)])
```

```{r Getting percentages for age categories}

#gets the total percentage of the population that each age category make up health region
percentage_census <- test %>% 
  mutate(lessten_p = (lessten_total/pop_total)*100, tens_p = (tens_total/pop_total)*100, twentys_p = (twentys_total/pop_total)*100, thirtys_p = thirtys_total/pop_total*100, fourtys_p = (fourtys_total/pop_total)*100, fiftys_p = (fiftys_total/pop_total)*100, sixtys_p = (sixtys_total/pop_total)*100, seventys_p = (seventys_total/pop_total)*100, eightys_p = (eightys_total/pop_total)*100, ninetyover_p = (ninetyover_total/pop_total)*100)

#selects only the columns pertaining to percentage that each age category makes up as well as the health region name 
percentage_census <- percentage_census %>%
  select(lessten_p, tens_p, twentys_p, thirtys_p, fourtys_p, fiftys_p, sixtys_p, seventys_p, eightys_p, ninetyover_p, "GEO_NAME")
percentage_census
```

```{r Merging age and pop. density dataframes; making under/over fourty categories}
#merges the dataframes for population density and percentage of the population that each age category makes up per health region
pcntge_density <- merge(percentage_census,pop_density, by = "GEO_NAME")
pcntge_density

#group age categories together into two categories, under forty and above forty, this is because a majority of tfw coming into canada are under forty, also makes a new data frame with those two categories and health region
pcntge_density2 <- pcntge_density %>% mutate(lessfourty = rowSums(pcntge_density[2:5]), greaterfourty = rowSums(pcntge_density[6:11])) %>% dplyr::select(
  "GEO_NAME",
  lessfourty,
  greaterfourty,
  population_density
  
)
pcntge_density2
#exported dataframe so that it can be cleaned further and compiled with others manually, using excel
write.csv(pcntge_density2, "pcntge_density.csv")

```

```{r Getting Percentage for Age Category - Cases}
#imported cleaned case_age.csv, which also had number of cases split into two categories, under and over/equal to forty, like the census data
worker_age <- read_excel("worker_age.xlsx")

#gets the percentage of cases over/equal to and under forty
cases_ages <- worker_age %>% mutate(totalcases = cases_above_40 + cases_under_40, clessfourty_p = cases_under_40/totalcases, cgreaterfourty_p = cases_above_40/totalcases) %>% dplyr::select(
  "health_region",
  clessfourty_p,
  cgreaterfourty_p,
  province.x
)
cases_ages

#exported dataframe so that it can be cleaned further and compiled with others manually, using excel
write.csv(cases_ages, "cases_age.csv")
```


```{r Compiling Num.Workers per region}

# Importing cleaned data sets from Excel for number of migrant agricultural workers in each province. Data set orginally made in data_cleaning_canada.rmd

on_workers = read_excel("on_workers")
ontario_worker <- on_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 

bc_workers = read_excel("bc_workers")
bc_worker<- bc_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 

ma_workers = read_excel("ma_workers")
ma_worker<- ma_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
ma_worker


al_workers = read_excel("alberta_workers")
al_worker<- al_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
    
 ) 
al_worker

nl_workers = read_excel("nl_workers")
nl_worker<- nl_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
nl_worker

ns_workers = read_excel("ns_workers")
ns_worker<- ns_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
ns_worker


pei_workers = read_excel("pei_workers")
pei_worker<- pei_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
pei_worker

sa_workers = read_excel("sa_workers")
sa_worker<- sa_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
sa_worker

qu_workers = read_excel("qu_workers")
qu_worker<- qu_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
qu_worker


nb_workers = read_excel("nb_workers")
nb_worker<- nb_workers%>%
    dplyr::select(
    "Health Unit",
    "Province",
    "Num Workers"
 ) 
nb_worker
```

```{r Merging provincial worker count}

# Summarizing number of workers in each health region for all provincesm, uses rbind to combine all dataframes made in previous chunk

workers <-rbind(ontario_worker,bc_worker,ma_worker,al_worker,nl_worker,ns_worker,pei_worker,sa_worker,qu_worker,nb_worker)
workers_summary <- aggregate(workers$"Num Workers", by=list("Health Unit"=workers$`Health Unit`),FUN=sum)
colnames(workers_summary)[2]<-"number_of_workers"
colnames(workers_summary)[1]<-"health_region"
workers_summary

#exported dataframe so that it can be cleaned further and compiled with others manually
write_csv(workers_summary,"workers_hr.csv")
```

```{r Finding medians for num. workers/ pop. density}
#census_cases_workers_age was result of workers_hr, cases_age and percentige_density csvs being cleaned and merged together
census_cases_workers <- read_excel("census_cases_workers_age.xlsx")

#obtains the median population density for all health region
worker_median <- median(census_cases_workers_age$num_workers)
```

```{r Splitting regions by pop. density (2 categories)}
#splits health regions into two categories, using the median as the cutt-off point
tableau_dataset <- census_cases_workers_age %>% mutate(Density = ifelse(pop_density > 27.15, "Higher Density", "Lower Density"))
```

```{r Splitting Regions by num. workers (no workers, > 0 workers}
#splits health regions into two categories, those with and without migrant workers 
tableau_dataset <- tableau_dataset %>% mutate(workers = ifelse(num_workers == 0, "No Migrant Workers", "Migrant Workers"))
tableau_dataset

write_csv(tableau_dataset, "tableau_data.csv")
```


